### ISSUE TITLE
Parse 1042-S

### ISSUE THREAD

**Issue by esemi** [cdump/investments#10]
На протяжение года IB автоматически удерживают с россиян 10% withholding tax с акций, ETF, ADR, а к 15 февраля пересматривают, что было в составе ETF и могут уменьшить налог соответственно.
Вроде бы эти корректировки задним числом суммы налога по дивам не видны нигде, кроме 1042-S формы. 
Выходит, в нашу налоговую мы недоплатим 10%, которые нам вернули)

**Comment by cdump** [comment]
В разделе tax можно скачать два отчета - 1042S (pdf) и просто dividends report (csv), и нас скорее интересует второй отчет.
В нем детальная информация про дивы + уплаченные налоги, в том числе в других странах, данные по США в нем у меня за 4 года совпадают с 1042S (только в csv с центами, а в 1042S - сумма округленная до ближайшего целого доллара)

**Comment by esemi** [comment]
хмм, тогда предлагаю дождаться реального кейса. У меня пока нет отчётов по таксе, я просто себе зафиксировал что есть такая особенность с возвратом налога задним числом. Думаю в феврале будет видно, у меня есть пара бондовых etf)
