### ISSUE TITLE
Inactivity fees support

### ISSUE THREAD

**Issue by esemi** [cdump/investments#11]
У IB есть комиссия за неактивность от $20 до $0 в месяц. Сумму данных комиссий за год можно вычесть из доходов от сделок за следующие три года. Хочется учесть это в калькуляции

**Comment by cdump** [comment]
Можно ссылку на статью налогового кодекса, которая говорит что на этот расход можно уменьшать доход? 
По курсу ЦБ на какой день эту комиссию переводить в рубли?
И какой конкретно код дохода уменьшать - ведь например акции и опционы на фьючерсы вносятся в декларацию разными кодами.

**Comment by esemi** [comment]
214.1 НК РФ п.10

`расходами по операциям с ценными бумагами и расходами по операциям с производными финансовыми инструментами признаются документально подтвержденные и фактически осуществленные налогоплательщиком расходы, связанные с приобретением, реализацией, хранением и погашением ценных бумаг, с совершением операций с производными финансовыми инструментами, с исполнением и прекращением обязательств по таким сделкам.`
...
Комис за неактивность наверное сюда
`3) оплата услуг, оказываемых профессиональными участниками рынка ценных бумаг, а также **биржевыми посредниками** и клиринговыми центрами;`
либо сюда
`12) другие расходы, непосредственно связанные с операциями с ценными бумагами`

Комис за депо - сюда
`8) оплата услуг лиц, осуществляющих ведение реестра;`

Комис за сделку бирже
`7) биржевой сбор (комиссия);`

**Comment by esemi** [comment]
Открытие рассчитывает также
![image](https://user-images.githubusercontent.com/4115497/94698281-cf438b80-0341-11eb-88c1-ff7aa4dadad9.png)
даже расходы на вывод средств вычитает

**Comment by esemi** [comment]
Для расчёта курса комиса следует использовать дату сделки, поскольку комис списывается в тот же день, без всяких Т+2

**Comment by esemi** [comment]
Закрываем?

**Comment by cdump** [comment]
Закрываем, ведь сделано)
