### ISSUE TITLE
Show tax percent in dividends table

### ISSUE THREAD

**Issue by esemi** [cdump/investments#15]
Поговаривают, не всякие диво-подобные выплаты проходят по ставке 10% налога для нерезов в США. Хочется вывести ставку в таблице
![image](https://user-images.githubusercontent.com/4115497/94842980-b4961300-0424-11eb-8690-c2d6220d5595.png)

**Comment by cdump** [comment]
А для чего это может пригодиться?

Ведь при заполнении декларации по дивидендам указывается сумма выплаты + сумма уплаченного налога (который можно зачесть), а не проценты или сумма доплаты.

P.S. я выводил проценты для теста когда-то - везде было 10%, но не увидел смысла оставлять по причинам выше

**Comment by esemi** [comment]
С целью не пропустить тот случай, когда IB задним числом вернёт часть уплаченного налога
У меня только за этот год есть отчёт IB, не могу проверить как оно точно работает - либо они уменьшают налог задним числом в прошедшем году либо в новом году добавляют выплату налога обратно

**Comment by esemi** [comment]
Предлагаю сделать режим --details и в нём выводить чуть более подробную инфу, в том числе эту

**Comment by cdump** [comment]
Добавил (в `master`'e) `--verbose` ключик, который отключает "схлопывание" reversal dividends + выводит tax_rate для дивидендов
Пока предлагаю все подобное под этим ключем делать, если станет перегруженно - можно будет сделать более детальные опции отображения

@esemi посмотри, если этого достаточно - можно закрывать issue

**Comment by esemi** [comment]
Спасибо, думаю пока хватит)
