### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by esemi** [cdump/investments#26]
Думаю было бы полезно писать чейнджлог по релизам https://pypi.org/project/investments/#history
Банально, понимать где могло сломаться и почему)

**Comment by cdump** [comment]
И для релизов на гитхабе - тоже полезно было бы.
Только нужен автоматизированный способ (github actions), который бы собрал коммиты с пред. релиза (пред. тэга) и оформил все сам

**Comment by cdump** [comment]
Добавил автогенерацию изменений с пред. релиза - https://github.com/cdump/investments/releases/tag/0.1.23
На pypi не нашел где такое размещать, так что на гитхабе только (релиза одинаковы и создаются в гитхабе/выкаладываются в pypi автоматически)
