### ISSUE TITLE
Offshore dividends tax

### ISSUE THREAD

**Issue by xkrt** [cdump/investments#31]
Привет, спасибо за работу над `ibtax`!

Кажется я нашёл недоработку. У меня в портфеле есть 15 шт. IVZ, которая платит дивиденды. IB не удерживает налог с этих дивов, поскольку компания зарегистрирована в оффшоре (Бермуды). Соответственно в Activity statement записи о этих дивидендах есть в разеделе Dividends и нет в разделе Withholding Tax.

Насколько я понимаю, в этом случае я должен заплатить в налоговую РФ все 13% от этих дивов. При этом `ibtax` насчитывает tax_paid_rub = 0₽.

Урезанный output ibtax:
```
>>> DIVIDENDS <<<
                            amount tax_paid      rate amount_rub tax_paid_rub
N  ticker        date
4  (IVZ, Stock)  2020-09-01  2.33$       0$  73.8039₽    171.96₽        0.00₽
11 (IVZ, Stock)  2020-12-02  2.33$       0$  76.3203₽    177.83₽        0.00₽
```

JFYI насколько я вижу, "конкурирующий" тул https://github.com/KonishchevDmitry/investments верно указывет 22₽ и 23₽ к доплате соответственно.

**Comment by cdump** [comment]
Привет!
ibtax не рассчитывает для дивидендов сколько нужно доплатить, а показывает только сумму дивиденда и уже удержанный налог (tax_paid), т.е. в данном случае все отобразилось верно.
Сумма уплаты (либо доплаты) налога рассчитывается автоматически при заполнении декларации (я заполнял на nalog.ru и каждую выплату дивиденда вносил отдельно), в форме для дивидендов есть поля "сумма дивиденда" и "налог, уплаченный в другом государстве"

**Comment by xkrt** [comment]
@cdump спасибо за разъяснения!
