### ISSUE TITLE
Подсказать по алгоритму расчёта

### ISSUE THREAD

**Issue by demanuffacture** [cdump/investments#49]
Извините, наверное это не баг, но никак не могу понять - как программа выходит на сумму 159663.38 рублей в примере ниже? Ни в Excel, ни в калькуляторе не смог воспроизвести.
> ticker (VOO, Stock)
> trade_date 2019-01-16
> settle_date 2019-01-18
> quantity 10
> price 240.1975$
> fee -1.0000$
> total -2402.98$
> **total_rub -159663.38₽**
> settle_rate 66.4438₽
> fee_rate 67.0820₽
> profit_rub 0₽

**Comment by esemi** [comment]
Судя по всему это транзакция покупки?
Расчёт такой:
```
240.1975 * 10 * 66.4438 + 1 * 67.0820 = 159663.428505
```

Разница в 4.8 копейки скорее всего закопана в числах после двух знаков за запятой - флаг --verbose покажет числа в таблице без округлений

**Comment by demanuffacture** [comment]
Спасибо! С флагом стало понятнее, теперь в Excel воспроизвелось.
1) Рассчитывается цена 1 акции в рублях и зачем-то округляется до 2 знаков: ОКРУГЛ(240,1975*66,4438;2) = 15959,63 (без округления было бы 15959,63**465**)
2) Цена умножается на количество (10) и добавляется суммарная комиссия в рублях. Результат ещё раз округляется ОКРУГЛ(10*15959,63+1*67,082;2) = 159663,38
Округление в первом пункте, конечно, смущает.. останусь пока на Excel, благо сделок в 2020 было немного.

**Comment by esemi** [comment]
@demanuffacture Все расчёты внутри тулы идут без округления. До двух знаков округляется уже только на этапе вывода таблички, поскольку цифры вида 10.12345678964545 нечитабельны)
