### ISSUE TITLE
FIFO profit calculation bug (?)

### ISSUE THREAD

**Issue by ivazin** [cdump/investments#8]
Вот два тестовых лога трейдов, отличающиеся последней транзакцией: в одном она цельная, в другом — разделена на 2 (переход через момент, когда портфель пуст).

По профиту они должны быть идентичны, но почему-то результаты программы оочень отличаются:
<img width="1368" alt="aaa" src="https://user-images.githubusercontent.com/27406797/94545313-09832f00-0255-11eb-9116-fb44c41e6e9a.png">
(или я что-то не так понимаю?)

**Comment by cdump** [comment]
Похоже на баг - в первом случае ошибочно учелся профит от короткой позиции до ее закрытия.
Можешь выложить эти два тестовых отчета, на которых запускался ibtax?

**Comment by ivazin** [comment]
Легко, вот:
[Archive.zip](https://github.com/cdump/investments/files/5298854/Archive.zip)

**Comment by cdump** [comment]
Думаю что поправил в v0.1.19 - можно проверять

**Comment by ivazin** [comment]
Обновился до v0.1.19, но кажется, ничего не изменилось

**Comment by cdump** [comment]
Проверил внимательнее, на данных из Archive.zip еще один непокрытый тестами кейс был - теперь в v0.1.20 все поправлено

**Comment by cdump** [comment]
@ivazin можшь проверить еще раз?

**Comment by cdump** [comment]
Считаем что исправлено, если повторится - заведи отдельный тикет
