### ISSUE TITLE
Trade fees support

### ISSUE THREAD

**Issue by esemi** [cdump/investments#9]
Хочется добавлять комиссии за трейд (покупка/продажа) в расход/доход по сделке.

**Comment by cdump** [comment]
Пример сделки:
```
1 Dec 2019 - Buy 100 TICKER, fee=10$
15 Dec 2019 - Sell 50 TICKER, fee=5$
2 Feb 2020 - Sell 50 TICKER, fee=5$
```

Какую коммисию нужно учесть за 2019 год, когда при закрытии сделки 15 декабря использовалась только часть акций с открытой сделки 1 декабря? Или нужно просто считать коммисию по сделкам, а не по закрытым (FIFO) сделкам?

Нужно найти ссылки на конкретные части статей налогового кодекса, описывающие это, чтобы быть уверенным как точно считать правильно и с каким кодом это правильно вносить в декларацию

**Comment by esemi** [comment]
Пошёл копать, все эти правила выписывал себе по мере изучения темы на банках и других ресурсах, но вот пруфы не искал. Вангую, что в нашем НК всё описано вилами по воде и никто не распишет как быть в приведённой ситуации)
По логике - комис за покупку делится равными долями между каждым лотом и также учитывается при продаже. То есть вместо суммы сделки надо хранить итоговую стоимость одного лота (сумма сделки + комис) / кол-во лотов

**Comment by esemi** [comment]
Что уменьшить на комиссию за сделку можно - 214.1 НК РФ п.10.3
Порядок учёта - разве что в разъяснительных письмах искать, в НК такого не нашёл

**Comment by FlameFactory** [comment]
[Отсюда:](https://journal.tinkoff.ru/invest-declare/)
> Комиссии надо переводить в рубли по курсу на дату списания комиссии по отчету брокера. Налоговым кодексом предусмотрен пересчет в рубли отдельно доходов и расходов, а не общего финансового результата. 

То есть, думаю что второй вариант -- нужно просто считать коммисию по сделкам

**Comment by esemi** [comment]
Изучаю как Открытие брокер работает с комиссиями за сделки при расчёте налогов.
Дано:

| date |  qty | cost | fee |
| --- | --- | --- | --- |
| 2018-07-30 | 10 | 5 855.00 | 14.05 |
| 2018-07-31 | 10 | 5 852.00 | 14.04 |
| 2018-07-31 | -20 | 12 580.00 | 30.50 |
| 2018-12-13 | 260 | 160 680.00 | 385.63 |
| 2019-02-25 | -210 | 136878.00 | 328,5 |
| 2019-02-26 | -50 | 32590.00 | 78.22 |

Кейса сложнее у меня нет, а в отчёте по налогам результаты схлопнуты по тикеру (то есть не посмотреть расчёт налога по отдельной сделке).

Тем не менее, в данном кейсе открывашка насчитала налоговой базы по данному тикеру:
2018 год `814,41`
2019 год `7995,65`

Считаем налоговую базу сами:
**2018**
Без учёта комиссий за сделку: (5855 + 5852 - 12580) * -1 = 873
С комиссиями: 873 - 14.05 - 14.04 - 30.50 = **814,41**

**2019**
Без учёта комиссий за сделку: (160680 - 136878 - 32590) * -1 = 8788
С комиссиями: 8788 - 385.63 - 328,5 - 78.22 = **7995,65**

Как видим, комиссия за сделку в размере 385.63 перескочила с 2018 года в 2019, когда была продажа и уменьшила базу налога на этот расход.

**Comment by esemi** [comment]
> 1 Dec 2019 - Buy 100 TICKER, fee=10$
> 15 Dec 2019 - Sell 50 TICKER, fee=5$
> 2 Feb 2020 - Sell 50 TICKER, fee=5$

Для данного кейса я бы считал следующим образом.
Дано:
| date |  qty | cost | fee | cost +/- fee |
| --- | --- | --- | --- | --- |
| 2019-12-01 | 100 | 1000 | 10 | 1010 |
| 2019-12-15 | -50 | 600 | 5 | 595 |
| 2020-02-02 | -50 | 600 | 5 | 595 |

_Сумма сделки нам для расчёта нужна, набил для примера "купили за 1000, продали за 1200"_

Считаем базу налога:
**2019**
Без комиссий за сделку: 600 - 500 = 100
С комиссиями: 595 - (1010 / 100 * 50) = **90**

**2020**
ctrl-c + ctrl-v

По сути для расчёта начальную таблицу сделок мы приводим к такой
| date |  qty | cost | fee | cost +/- fee |
| --- | --- | --- | --- | --- |
| 2019-12-01 | 50 | 500 | 5 | 505 |
| 2019-12-01 | 50 | 500 | 5 | 505 |
| 2019-12-15 | -50 | 600 | 5 | 595 |
| 2020-02-02 | -50 | 600 | 5 | 595 |

Собственно и для расчёта без комиссий мы табличку приводим к такому же виду

**Comment by esemi** [comment]
IB тоже комис вычитает из реализованной прибыли
![image](https://user-images.githubusercontent.com/4115497/95300150-74e98400-0887-11eb-94b7-a13048a8a12f.png)

818.20 - 806.20 - 1 - 1.02 = **9.98**
Столько прибыли и IB в отчёте насчитал

**Comment by esemi** [comment]
Подсчёт в долларах надо делать чуть хитрее, чем в рублях: комис и сумму сделки нужно переводить в рубли по курсу за разные даты, так что суммировать их в долларах некорректно.
По этой причине нельзя просто взять профит, который IB на своей стороне считает (9.98 из примера выше)

**Comment by esemi** [comment]
Подумываю втащить дату транзакции в Money и вести все расчёты в рублях по курсу на дату
@cdump пропустишь такое?)

**Comment by cdump** [comment]
дата в Money мне очень сильно не нравится
Лучше просто добавить в pandas DataFrame поле с date (дата сделки, а не поставки) и доставать exchange_rate на эту дату тоже, и по нему переводить комиссию по каждой сделке в рубли

**Comment by esemi** [comment]
Принято, попробую обойтись без монументальных правок)

**Comment by cdump** [comment]
Тоже посмотрел [отчет Открытия в Excel](https://lk.open-broker.ru/brokerReports/taxes), там расписано ФИФО и прочие подробности.

В отчете по сделкам:
```
19.02.2020: куплено 254шт (всего 188239.4) по 741.1р (комисс 107.3)
20.03.2020: продан 108шт (всего 52531.2) по 486.4р (комисс 29.94)
```

Эти сделки в ФИФО рассчета налогов:
```
затраты 29,94 + 45,62362205 = 75,56362205
```
получается они посчитали затраты на покупку как `(108 / 254) * 107.3 = 45.6236220472`

что подтверждает способ, который предложил @esemi

**Comment by cdump** [comment]
смержено в мастер
